### ISSUE TITLE
LeetCode Guide

### ISSUE THREAD

**Issue by junxnone** [junxnone/leetcode#1]
## TO-DO
- [ ] [Array and String](https://leetcode.com/explore/learn/card/array-and-string/)
- [ ] [Binary Tree](https://leetcode.com/explore/learn/card/data-structure-tree/)
- [ ] [Queue & Stack](https://leetcode.com/explore/learn/card/queue-stack/)
- [ ] [Recursion](https://leetcode.com/explore/featured/card/recursion-i/)

## Reference

- [LeetCode](https://leetcode.com/)
- [LeetCode CN](https://leetcode-cn.com/)
- [awesome-algorithm - apachecn](https://github.com/apachecn/awesome-algorithm)
- [awesome-leetcode](https://github.com/jindongwang/awesome-leetcode)
- [hello-algo](https://www.hello-algo.com/)

## 正确的打开方式

- 选题
- 思考 -> 做题验证
- 查看别人思路 -> 思考验证
- 查看别人题解 ->思考
- 总结
